//! Constants for the application, i.e. for all modules.
use crate::types::TPrecision;

/// Default precision for the calculation. The time needed to calculate the approximation is
/// proportional to the precision, in a development environment it will probably take
/// 3x longer than in a production environment due to instrumentation. Each increment of the
/// precision will take ca. 3x longer to calculate.
#[cfg(not(debug_assertions))]
pub const DEFAULT_PRECISION: TPrecision = 8;
#[cfg(debug_assertions)]
pub const DEFAULT_PRECISION: TPrecision = 7;

/// Where is the worker loader located? It will be generated by the trunk build process.
pub const WORKER_LOADER_URL: &str = "worker_loader.js";