name: Security audit

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["**/Cargo.toml"]
  schedule:
    - cron: "42 3 * * *"

permissions:
  contents: read

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
